//! Provider-neutral persisted project/session/conversation state.
//!
//! Persisted state contains stable identifiers, user-visible conversation text, and user choices.
//! It deliberately excludes filesystem authority, secrets, raw tool/process output, resolved model
//! catalogs, command approvals, or connection-generation state. Every loaded runtime identifier
//! must be re-corroborated before it becomes live authority again.

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use vibecoder_domain::{ConversationId, ProjectId, Result, SessionId, VibeCoderError};
use vibecoder_routing::{ModelRoutePolicyConfig, ModelRouteTargetConfig};

pub const PROJECT_STATE_SCHEMA_V1: u32 = 1;
pub const CONVERSATION_STATE_SCHEMA_V1: u32 = 1;
pub const MAX_PERSISTED_PROJECTS: usize = 4096;
pub const MAX_PERSISTED_CONVERSATIONS_PER_PROJECT: usize = 512;
pub const MAX_PERSISTED_STATE_BYTES: usize = 256 * 1024;
pub const MAX_PERSISTED_CONVERSATION_BYTES: usize = 16 * 1024 * 1024;
pub const MAX_CONVERSATION_MESSAGES: usize = 4096;
pub const MAX_CONVERSATION_MESSAGE_BYTES: usize = 256 * 1024;
pub const MAX_CONVERSATION_TEXT_BYTES: usize = 12 * 1024 * 1024;
pub const MAX_CONVERSATION_TITLE_BYTES: usize = 200;
pub const MAX_RUNTIME_ID_BYTES: usize = 64;
pub const MAX_SESSION_ID_BYTES: usize = 128;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PersistenceCapabilities {
    pub project_registry: bool,
    pub session_binding: bool,
    pub model_preference: bool,
    pub route_policy: bool,
    pub conversation_registry: bool,
    pub conversation_messages: bool,
    pub atomic_replace: bool,
    pub secrets_persisted: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PersistedAgentSession {
    /// Stable adapter id such as `jcode-harness`. This is identity metadata, not executable input.
    pub runtime_id: String,
    pub session_id: SessionId,
    #[serde(default)]
    pub preferred_model: Option<ModelRouteTargetConfig>,
}

impl PersistedAgentSession {
    pub fn validate(&self) -> Result<()> {
        validate_runtime_id(&self.runtime_id)?;
        validate_session_id(&self.session_id)?;
        if let Some(model) = &self.preferred_model {
            model.validate()?;
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PersistedProjectState {
    pub schema: u32,
    /// Monotonic compare-and-swap revision. Revision zero is valid only for first creation.
    pub revision: u64,
    pub project_id: ProjectId,
    /// Legacy single-session crash marker retained for backwards compatibility with Parts 16-31.
    #[serde(default)]
    pub session_creation_pending: bool,
    /// Legacy project session retained for backwards compatibility. Part 34 conversations use the
    /// separate conversation registry so one project can have multiple independent chats.
    #[serde(default)]
    pub agent_session: Option<PersistedAgentSession>,
    #[serde(default)]
    pub route_policy: Option<ModelRoutePolicyConfig>,
}

impl PersistedProjectState {
    pub const fn new(project_id: ProjectId) -> Self {
        Self {
            schema: PROJECT_STATE_SCHEMA_V1,
            revision: 0,
            project_id,
            session_creation_pending: false,
            agent_session: None,
            route_policy: None,
        }
    }

    pub fn validate(&self) -> Result<()> {
        if self.schema != PROJECT_STATE_SCHEMA_V1 {
            return Err(persistence_error("project_state_schema_unsupported"));
        }
        if self.session_creation_pending && self.agent_session.is_some() {
            return Err(persistence_error("project_state_session_pending_conflict"));
        }
        if let Some(session) = &self.agent_session {
            session.validate()?;
        }
        if let Some(policy) = &self.route_policy {
            policy.validate()?;
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConversationRole {
    User,
    Assistant,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PersistedConversationMessage {
    /// Dense zero-based sequence generated by VibeCoder. It is ordering metadata, not a clock.
    pub sequence: u64,
    pub role: ConversationRole,
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PersistedConversation {
    pub schema: u32,
    /// Monotonic compare-and-swap revision. Revision zero is valid only for first creation.
    pub revision: u64,
    pub conversation_id: ConversationId,
    pub project_id: ProjectId,
    /// Written before Jcode session creation. A true marker blocks turns/resume until explicit
    /// recovery or cleanup, so an app/process crash cannot turn an ambiguous session into authority.
    pub session_creation_pending: bool,
    #[serde(default)]
    pub agent_session: Option<PersistedAgentSession>,
    /// Written after the user message is committed and before inference begins. A crash leaves this
    /// marker visible instead of pretending the turn completed.
    #[serde(default)]
    pub turn_pending: bool,
    #[serde(default)]
    pub title: Option<String>,
    #[serde(default)]
    pub messages: Vec<PersistedConversationMessage>,
}

impl PersistedConversation {
    pub fn pending_creation(conversation_id: ConversationId, project_id: ProjectId) -> Self {
        Self {
            schema: CONVERSATION_STATE_SCHEMA_V1,
            revision: 0,
            conversation_id,
            project_id,
            session_creation_pending: true,
            agent_session: None,
            turn_pending: false,
            title: None,
            messages: Vec::new(),
        }
    }

    pub fn validate(&self) -> Result<()> {
        if self.schema != CONVERSATION_STATE_SCHEMA_V1 {
            return Err(persistence_error("conversation_state_schema_unsupported"));
        }
        match (self.session_creation_pending, self.agent_session.as_ref()) {
            (true, None) | (false, Some(_)) => {}
            _ => return Err(persistence_error("conversation_session_state_invalid")),
        }
        if let Some(session) = &self.agent_session {
            session.validate()?;
        }
        if self.session_creation_pending && (self.turn_pending || !self.messages.is_empty()) {
            return Err(persistence_error("conversation_creation_pending_payload_invalid"));
        }
        if let Some(title) = &self.title {
            if title.is_empty()
                || title.len() > MAX_CONVERSATION_TITLE_BYTES
                || title.trim() != title
                || title.chars().any(char::is_control)
            {
                return Err(persistence_error("conversation_title_invalid"));
            }
        }
        if self.messages.len() > MAX_CONVERSATION_MESSAGES {
            return Err(persistence_error("conversation_message_limit_exceeded"));
        }
        let mut total = 0usize;
        for (index, message) in self.messages.iter().enumerate() {
            if message.sequence != index as u64 {
                return Err(persistence_error("conversation_message_sequence_invalid"));
            }
            if message.text.is_empty()
                || message.text.len() > MAX_CONVERSATION_MESSAGE_BYTES
                || message.text.contains('\0')
            {
                return Err(persistence_error("conversation_message_invalid"));
            }
            total = total
                .checked_add(message.text.len())
                .ok_or_else(|| persistence_error("conversation_text_too_large"))?;
            if total > MAX_CONVERSATION_TEXT_BYTES {
                return Err(persistence_error("conversation_text_too_large"));
            }
        }
        if self.turn_pending
            && !matches!(
                self.messages.last().map(|message| message.role),
                Some(ConversationRole::User)
            )
        {
            return Err(persistence_error("conversation_pending_turn_invalid"));
        }
        Ok(())
    }

    pub fn append_message(&mut self, role: ConversationRole, text: String) -> Result<()> {
        if text.is_empty() || text.len() > MAX_CONVERSATION_MESSAGE_BYTES || text.contains('\0') {
            return Err(persistence_error("conversation_message_invalid"));
        }
        if self.messages.len() >= MAX_CONVERSATION_MESSAGES {
            return Err(persistence_error("conversation_message_limit_exceeded"));
        }
        let total = self
            .messages
            .iter()
            .try_fold(0usize, |total, message| total.checked_add(message.text.len()))
            .and_then(|total| total.checked_add(text.len()))
            .ok_or_else(|| persistence_error("conversation_text_too_large"))?;
        if total > MAX_CONVERSATION_TEXT_BYTES {
            return Err(persistence_error("conversation_text_too_large"));
        }
        let sequence = self.messages.len() as u64;
        self.messages.push(PersistedConversationMessage {
            sequence,
            role,
            text,
        });
        Ok(())
    }
}

#[async_trait]
pub trait ProjectStateStore: Send + Sync {
    fn capabilities(&self) -> PersistenceCapabilities;

    /// Create revision-zero state. Must fail if state already exists for this project.
    async fn create_project_state(&self, state: &PersistedProjectState) -> Result<()>;

    /// Compare-and-swap one existing state revision. `state.revision` must equal
    /// `expected_revision`; the store persists and returns revision+1.
    async fn update_project_state(
        &self,
        expected_revision: u64,
        state: &PersistedProjectState,
    ) -> Result<PersistedProjectState>;

    async fn load_project_state(
        &self,
        project_id: ProjectId,
    ) -> Result<Option<PersistedProjectState>>;

    async fn list_project_ids(&self, max_projects: usize) -> Result<Vec<ProjectId>>;

    async fn remove_project_state(&self, project_id: ProjectId) -> Result<()>;
}

#[async_trait]
pub trait ConversationStore: Send + Sync {
    async fn create_conversation(&self, conversation: &PersistedConversation) -> Result<()>;

    /// Compare-and-swap one existing conversation revision. The returned object has revision+1.
    async fn update_conversation(
        &self,
        expected_revision: u64,
        conversation: &PersistedConversation,
    ) -> Result<PersistedConversation>;

    async fn load_conversation(
        &self,
        project_id: ProjectId,
        conversation_id: ConversationId,
    ) -> Result<Option<PersistedConversation>>;

    async fn list_conversation_ids(
        &self,
        project_id: ProjectId,
        max_conversations: usize,
    ) -> Result<Vec<ConversationId>>;

    async fn remove_conversation(
        &self,
        project_id: ProjectId,
        conversation_id: ConversationId,
    ) -> Result<()>;

    async fn remove_project_conversations(&self, project_id: ProjectId) -> Result<()>;
}

fn validate_runtime_id(value: &str) -> Result<()> {
    if value.is_empty()
        || value.len() > MAX_RUNTIME_ID_BYTES
        || !value.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'-' | b'_' | b'.')
        })
    {
        return Err(persistence_error("project_state_runtime_id_invalid"));
    }
    Ok(())
}

fn validate_session_id(value: &SessionId) -> Result<()> {
    if value.0.is_empty()
        || value.0.len() > MAX_SESSION_ID_BYTES
        || !value
            .0
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
    {
        return Err(persistence_error("project_state_session_id_invalid"));
    }
    Ok(())
}

fn persistence_error(code: &'static str) -> VibeCoderError {
    VibeCoderError::Persistence(code.into())
}

#[cfg(test)]
mod tests {
    use super::*;
    use uuid::Uuid;

    #[test]
    fn state_contains_no_root_or_secret_fields() {
        let state = PersistedProjectState::new(ProjectId(Uuid::nil()));
        let json = serde_json::to_string(&state).unwrap();
        assert!(!json.contains("root"));
        assert!(!json.contains("secret"));
        assert!(!json.contains("api_key"));
    }

    #[test]
    fn rejects_bad_runtime_identity() {
        let mut state = PersistedProjectState::new(ProjectId(Uuid::nil()));
        state.agent_session = Some(PersistedAgentSession {
            runtime_id: "../../jcode".into(),
            session_id: SessionId("safe-session".into()),
            preferred_model: None,
        });
        assert!(state.validate().is_err());
    }

    #[test]
    fn conversation_requires_explicit_pending_or_verified_session_state() {
        let mut conversation = PersistedConversation::pending_creation(
            ConversationId(Uuid::nil()),
            ProjectId(Uuid::nil()),
        );
        assert!(conversation.validate().is_ok());
        conversation.append_message(ConversationRole::User, "impossible-before-session".into()).unwrap();
        assert!(conversation.validate().is_err());
        conversation.messages.clear();
        conversation.session_creation_pending = false;
        assert!(conversation.validate().is_err());
    }

    #[test]
    fn pending_turn_requires_last_user_message() {
        let mut conversation = PersistedConversation::pending_creation(
            ConversationId(Uuid::nil()),
            ProjectId(Uuid::nil()),
        );
        conversation.session_creation_pending = false;
        conversation.agent_session = Some(PersistedAgentSession {
            runtime_id: "jcode-harness".into(),
            session_id: SessionId("safe-session".into()),
            preferred_model: None,
        });
        conversation.append_message(ConversationRole::User, "hello".into()).unwrap();
        conversation.turn_pending = true;
        assert!(conversation.validate().is_ok());
        let before = conversation.clone();
        assert!(conversation
            .append_message(ConversationRole::User, "\0invalid".into())
            .is_err());
        assert_eq!(conversation, before);

        conversation.turn_pending = false;
        conversation
            .append_message(ConversationRole::Assistant, "hi".into())
            .unwrap();
        assert!(conversation.validate().is_ok());
    }
}
